version: '3'
services:
  automata-api:
    restart: always
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - '4000:4000'

    networks:
      - redesophy
    volumes:
      - ./cache-docker:/app/cache
  

networks:
  redesophy:
    driver: bridge