export default [
    {comand:'menu'},
    {comand:'sticker'},
    {comand:'comandos'},
    {comand:'toimg'},
    {comand:'ban',admin:true},
    {comand:'regras',admin:true},
    {comand:'add',admin:true},
    {comand:'marcar',admin:true},
    {comand:'antilink',admin:true},
    {comand:'antifake',admin:true},
    {comand:'boasvindas',admin:true},
    {comand:'antivendas',admin:true},
    {comand:'ytdownload'},
    {comand:'playmusic'},
    {comand:'playvideo'},
    {comand:'dj'}]